# サイトの設定
title: My Awesome Site
description: Welcome to my awesome site.
baseurl: "/sekisen-5s.github.io" # 例: '/project-name' サブディレクトリでホストする場合に設定します
url: "https://sekisen-5s.github.io/" # サイトのURL
permalink: /:categories/:year/:month/:day/:title/

# ビルド設定
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# 作者情報 (任意)
author:
  name: John Doe
  email: johndoe@example.com

# 排除するファイルやディレクトリ
exclude:
  - README.md

